name: Deploy to Dev

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment: "${{ 
      fromJson('{
        \"main\": \"prod\",
        \"dev\": \"dev\"
      }')[github.ref_name] 
    }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build . -t ${{ vars.IMAGE_TAG }}:latest -f Dockerfile.test
      - name: Run Tests in Docker
        run: docker run -e CI=true --rm ${{ vars.IMAGE_TAG }}:latest
      # - name: Build Production Docker Image
      #   run: docker build . -t ${{ vars.IMAGE_TAG }}:latest
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Push Docker Image
      #   run: docker push ${{ vars.IMAGE_TAG }}:latest

      # - name: Deploy to VPS
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ vars.VPS_HOST }}
      #     username: ${{ vars.VPS_USER }}
      #     key: ${{ secrets.VPS_KEY }}
      #     script: |
      #       docker pull ${{ vars.IMAGE_TAG }}:latest
      #       docker stop ${{ vars.CONTAINER_NAME }} || true
      #       docker rm ${{ vars.CONTAINER_NAME }} || true
      #       docker run -d \
      #         --name ${{ vars.CONTAINER_NAME }} \
      #         -p ${{ vars.VPS_PORT }}:80 \
      #         -e REACT_APP_APARTMENTS_URL=${{ vars.REACT_APP_APARTMENTS_URL }} \
      #         ${{ vars.IMAGE_TAG }}:latest


  deploy:
    runs-on: ubuntu-latest
    needs: test

    environment: "${{ 
      fromJson('{
        \"main\": \"prod\",
        \"dev\": \"dev\"
      }')[github.ref_name] 
    }}"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Production Docker Image
        run: docker build . -t ${{ vars.IMAGE_TAG }}:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push ${{ vars.IMAGE_TAG }}:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull ${{ vars.IMAGE_TAG }}:latest
            docker stop ${{ vars.CONTAINER_NAME }} || true
            docker rm ${{ vars.CONTAINER_NAME }} || true
            docker run -d \
              --name ${{ vars.CONTAINER_NAME }} \
              -p ${{ vars.VPS_PORT }}:80 \
              -e REACT_APP_APARTMENTS_URL=${{ vars.REACT_APP_APARTMENTS_URL }} \
              ${{ vars.IMAGE_TAG }}:latest